---
name: cmpsc-100-fall-2018-lab1
break: true
indent: 4
---
src/main:
    java:
        labone/DisplayOutput.java:
            --single 2 --language Java
            --multi 2 --language Java
            --fragment "println(" --count 4
            --fragment "new Date(" --count 1
writing/reflection.md:
    --paragraphs 1 --exact
    --words 150
--commits 7
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 4 --exact
